server:
  port: ${PORT} # Railway injecte dynamiquement le port

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

security:
  jwt:
    secret: ${JWT_SECRET}
  cookie:
    same-site: None
    secure: true

frontend:
  base-url: ${FRONTEND_BASE_URL}

